import os
import re
import secrets
import sqlite3
import uuid
from datetime import timedelta

from dotenv import load_dotenv
from flask import Flask, jsonify, request, send_from_directory
from flask_cors import CORS
from flask_jwt_extended import JWTManager, create_access_token, get_jwt_identity, jwt_required
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename

load_dotenv()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MASTER_DB = os.path.join(BASE_DIR, "memory_bridge_master.db")
FAMILY_DB_DIR = os.path.join(BASE_DIR, "databases")
UPLOAD_DIR = os.path.join(BASE_DIR, "uploads")
os.makedirs(FAMILY_DB_DIR, exist_ok=True)
os.makedirs(UPLOAD_DIR, exist_ok=True)

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY", "memory-bridge-dev-secret")
app.config["JWT_SECRET_KEY"] = os.getenv("JWT_SECRET_KEY", "memory-bridge-jwt-secret")
app.config["JWT_ACCESS_TOKEN_EXPIRES"] = timedelta(hours=8)
app.config["JWT_TOKEN_LOCATION"] = ["headers", "query_string"]
app.config["JWT_QUERY_STRING_NAME"] = "token"
app.config["JWT_QUERY_STRING_VALUE_PREFIX"] = ""
app.config["MAX_CONTENT_LENGTH"] = 25 * 1024 * 1024

CORS(app)
jwt = JWTManager(app)

ALLOWED_AUDIO_EXTENSIONS = {"webm", "wav", "mp3", "m4a", "ogg"}
TAG_KEYWORDS = {
    "childhood": ["childhood", "school", "school days", "child"],
    "family": ["family", "mother", "father", "grandmother", "grandfather", "parents"],
    "village": ["village", "farm", "fields", "gaon"],
    "festival": ["festival", "diwali", "holi", "wedding", "marriage"],
    "work": ["work", "job", "office", "business", "career"],
    "advice": ["advice", "lesson", "learned", "should", "remember"],
    "travel": ["travel", "trip", "journey", "train", "bus"],
    "food": ["food", "recipe", "kitchen", "cooking"],
}


def connect_master():
    connection = sqlite3.connect(MASTER_DB)
    connection.row_factory = sqlite3.Row
    return connection


def family_db_path(family_id):
    # The filename is generated by the server. Clients never choose it.
    if not re.fullmatch(r"[A-F0-9]{12}", family_id):
        raise ValueError("Invalid family id.")
    return os.path.join(FAMILY_DB_DIR, f"family_{family_id}.db")


def connect_family(family_id):
    connection = sqlite3.connect(family_db_path(family_id))
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return connection


def create_family_database(family_id):
    connection = connect_family(family_id)
    try:
        connection.executescript(
            """
            CREATE TABLE IF NOT EXISTS members (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER UNIQUE NOT NULL,
                name TEXT NOT NULL,
                email TEXT NOT NULL,
                relationship TEXT NOT NULL,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS memories (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                member_id INTEGER NOT NULL,
                memory_text TEXT,
                transcript TEXT,
                audio_filename TEXT,
                summary TEXT,
                tags TEXT,
                created_by INTEGER NOT NULL,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY(member_id) REFERENCES members(id)
            );
            """
        )
        connection.commit()
    finally:
        connection.close()


def init_master_database():
    connection = connect_master()
    try:
        connection.executescript(
            """
            CREATE TABLE IF NOT EXISTS families (
                id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                join_code TEXT UNIQUE NOT NULL,
                database_file TEXT NOT NULL,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                family_id TEXT NOT NULL,
                name TEXT NOT NULL,
                email TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'member',
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY(family_id) REFERENCES families(id)
            );
            """
        )
        connection.commit()
    finally:
        connection.close()


def clean_text(value, max_length=10000):
    if value is None:
        return ""
    return str(value).strip()[:max_length]


def allowed_audio(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_AUDIO_EXTENSIONS


def make_title(text, fallback="Family Memory"):
    words = re.findall(r"\S+", clean_text(text, 240))
    if not words:
        return fallback
    title = " ".join(words[:8]).strip(" .,!?:;")
    return title + ("..." if len(words) > 8 else "")


def make_summary(text):
    text = clean_text(text)
    if not text:
        return ""
    sentences = re.split(r"(?<=[.!?])\s+", text)
    useful = " ".join(sentences[:2]).strip()
    words = useful.split()
    return " ".join(words[:45]) + ("..." if len(words) > 45 else "")


def make_tags(text):
    lower = clean_text(text).lower()
    found = []
    for tag, keywords in TAG_KEYWORDS.items():
        if any(keyword in lower for keyword in keywords):
            found.append(tag)
    return found[:6]


def generate_join_code():
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    return "".join(secrets.choice(alphabet) for _ in range(8))


def create_token(user):
    return create_access_token(
        identity=str(user["id"]),
        additional_claims={"family_id": user["family_id"], "role": user["role"]},
    )


def user_payload(user, family):
    return {
        "id": user["id"],
        "name": user["name"],
        "email": user["email"],
        "role": user["role"],
        "family": {
            "id": family["id"],
            "name": family["name"],
            "join_code": family["join_code"],
        },
    }


def get_current_context():
    user_id = get_jwt_identity()
    connection = connect_master()
    try:
        user = connection.execute(
            "SELECT * FROM users WHERE id = ?", (int(user_id),)
        ).fetchone()
        if not user:
            return None, None
        family = connection.execute(
            "SELECT * FROM families WHERE id = ?", (user["family_id"],)
        ).fetchone()
        return user, family
    finally:
        connection.close()


def memory_to_dict(memory):
    return {
        "id": memory["id"],
        "title": memory["title"],
        "member_id": memory["member_id"],
        "family_member": memory["member_name"],
        "relationship": memory["relationship"],
        "memory_text": memory["memory_text"] or "",
        "transcript": memory["transcript"] or "",
        "summary": memory["summary"] or "",
        "tags": [tag for tag in (memory["tags"] or "").split(",") if tag],
        "audio_url": (
            f"/api/memories/{memory['id']}/audio"
            if memory["audio_filename"]
            else None
        ),
        "created_at": memory["created_at"],
    }


def find_memory(connection, memory_id):
    return connection.execute(
        """
        SELECT memories.*, members.name AS member_name, members.relationship
        FROM memories
        JOIN members ON members.id = memories.member_id
        WHERE memories.id = ?
        """,
        (memory_id,),
    ).fetchone()


init_master_database()


@app.get("/api/health")
def health():
    return jsonify({"status": "ok", "message": "Memory Bridge backend is running."})


@app.post("/api/families/create")
def create_family():
    data = request.get_json(silent=True) or {}
    family_name = clean_text(data.get("family_name"), 100)
    name = clean_text(data.get("name"), 100)
    email = clean_text(data.get("email"), 160).lower()
    password = str(data.get("password") or "")
    relationship = clean_text(data.get("relationship"), 80) or "Family Admin"

    if not family_name or not name or not email or not password:
        return jsonify({"message": "Family name, name, email and password are required."}), 400
    if len(password) < 6:
        return jsonify({"message": "Password must contain at least 6 characters."}), 400
    if "@" not in email:
        return jsonify({"message": "Please enter a valid email address."}), 400

    connection = connect_master()
    family_id = uuid.uuid4().hex[:12].upper()
    join_code = generate_join_code()
    while connection.execute(
        "SELECT 1 FROM families WHERE join_code = ?", (join_code,)
    ).fetchone():
        join_code = generate_join_code()

    try:
        if connection.execute("SELECT 1 FROM users WHERE email = ?", (email,)).fetchone():
            return jsonify({"message": "An account with this email already exists."}), 409

        connection.execute(
            "INSERT INTO families (id, name, join_code, database_file) VALUES (?, ?, ?, ?)",
            (family_id, family_name, join_code, f"family_{family_id}.db"),
        )
        cursor = connection.execute(
            """
            INSERT INTO users (family_id, name, email, password_hash, role)
            VALUES (?, ?, ?, ?, 'admin')
            """,
            (family_id, name, email, generate_password_hash(password)),
        )
        user_id = cursor.lastrowid
        connection.commit()

        create_family_database(family_id)
        family_connection = connect_family(family_id)
        try:
            family_connection.execute(
                """
                INSERT INTO members (user_id, name, email, relationship)
                VALUES (?, ?, ?, ?)
                """,
                (user_id, name, email, relationship),
            )
            family_connection.commit()
        finally:
            family_connection.close()

        user = connection.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
        family = connection.execute("SELECT * FROM families WHERE id = ?", (family_id,)).fetchone()
        token = create_token(user)
        return jsonify({
            "token": token,
            "user": user_payload(user, family),
            "message": "Family created successfully. Share the join code with your family members.",
        }), 201
    except Exception:
        connection.rollback()
        family_path = os.path.join(FAMILY_DB_DIR, f"family_{family_id}.db")
        if os.path.exists(family_path):
            os.remove(family_path)
        raise
    finally:
        connection.close()


@app.post("/api/families/join")
def join_family():
    data = request.get_json(silent=True) or {}
    join_code = clean_text(data.get("join_code"), 8).upper()
    name = clean_text(data.get("name"), 100)
    email = clean_text(data.get("email"), 160).lower()
    password = str(data.get("password") or "")
    relationship = clean_text(data.get("relationship"), 80)

    if not join_code or not name or not email or not password or not relationship:
        return jsonify({"message": "Join code, name, email, password and relationship are required."}), 400
    if len(password) < 6:
        return jsonify({"message": "Password must contain at least 6 characters."}), 400

    connection = connect_master()
    try:
        family = connection.execute(
            "SELECT * FROM families WHERE join_code = ?", (join_code,)
        ).fetchone()
        if not family:
            return jsonify({"message": "Family join code was not found."}), 404
        if connection.execute("SELECT 1 FROM users WHERE email = ?", (email,)).fetchone():
            return jsonify({"message": "An account with this email already exists."}), 409

        cursor = connection.execute(
            """
            INSERT INTO users (family_id, name, email, password_hash, role)
            VALUES (?, ?, ?, ?, 'member')
            """,
            (family["id"], name, email, generate_password_hash(password)),
        )
        user_id = cursor.lastrowid
        connection.commit()

        family_connection = connect_family(family["id"])
        try:
            family_connection.execute(
                """
                INSERT INTO members (user_id, name, email, relationship)
                VALUES (?, ?, ?, ?)
                """,
                (user_id, name, email, relationship),
            )
            family_connection.commit()
        finally:
            family_connection.close()

        user = connection.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
        token = create_token(user)
        return jsonify({
            "token": token,
            "user": user_payload(user, family),
            "message": "You joined the family successfully.",
        }), 201
    finally:
        connection.close()


@app.post("/api/auth/login")
def login():
    data = request.get_json(silent=True) or {}
    email = clean_text(data.get("email"), 160).lower()
    password = str(data.get("password") or "")

    connection = connect_master()
    try:
        user = connection.execute(
            "SELECT * FROM users WHERE email = ?", (email,)
        ).fetchone()
        if not user or not check_password_hash(user["password_hash"], password):
            return jsonify({"message": "Invalid email or password."}), 401

        family = connection.execute(
            "SELECT * FROM families WHERE id = ?", (user["family_id"],)
        ).fetchone()
        token = create_token(user)
        return jsonify({"token": token, "user": user_payload(user, family)})
    finally:
        connection.close()


@app.get("/api/auth/me")
@jwt_required()
def current_user():
    user, family = get_current_context()
    if not user:
        return jsonify({"message": "User not found."}), 404
    return jsonify(user_payload(user, family))


@app.get("/api/family")
@jwt_required()
def family_details():
    user, family = get_current_context()
    if not user or not family:
        return jsonify({"message": "Family not found."}), 404

    connection = connect_family(family["id"])
    try:
        members = connection.execute(
            """
            SELECT id, user_id, name, email, relationship, created_at
            FROM members ORDER BY name
            """
        ).fetchall()
        return jsonify({
            "id": family["id"],
            "name": family["name"],
            "join_code": family["join_code"],
            "role": user["role"],
            "members": [dict(member) for member in members],
        })
    finally:
        connection.close()


@app.get("/api/memories")
@jwt_required()
def list_memories():
    user, family = get_current_context()
    if not user or not family:
        return jsonify({"message": "Family not found."}), 404

    query = clean_text(request.args.get("q"), 120)
    connection = connect_family(family["id"])
    try:
        sql = """
            SELECT memories.*, members.name AS member_name, members.relationship
            FROM memories
            JOIN members ON members.id = memories.member_id
        """
        params = []
        if query:
            pattern = f"%{query}%"
            sql += """
                WHERE memories.title LIKE ?
                   OR members.name LIKE ?
                   OR members.relationship LIKE ?
                   OR memories.memory_text LIKE ?
                   OR memories.transcript LIKE ?
                   OR memories.tags LIKE ?
            """
            params = [pattern] * 6
        sql += " ORDER BY memories.created_at DESC"
        memories = connection.execute(sql, params).fetchall()
        return jsonify([memory_to_dict(memory) for memory in memories])
    finally:
        connection.close()


@app.post("/api/memories")
@jwt_required()
def create_memory():
    user, family = get_current_context()
    if not user or not family:
        return jsonify({"message": "Family not found."}), 404

    try:
        member_id = int(request.form.get("member_id", "0"))
    except ValueError:
        member_id = 0

    title = clean_text(request.form.get("title"), 180)
    memory_text = clean_text(request.form.get("memory_text"))
    transcript = clean_text(request.form.get("transcript"))

    connection = connect_family(family["id"])
    try:
        member = connection.execute(
            "SELECT * FROM members WHERE id = ?", (member_id,)
        ).fetchone()
        if not member:
            return jsonify({"message": "Please select a valid family member."}), 400

        audio_filename = None
        audio = request.files.get("audio")
        if audio and audio.filename:
            original = secure_filename(audio.filename)
            if not allowed_audio(original):
                return jsonify({"message": "Unsupported audio format."}), 400
            extension = original.rsplit(".", 1)[1].lower()
            audio_filename = f"{uuid.uuid4().hex}.{extension}"
            audio.save(os.path.join(UPLOAD_DIR, audio_filename))

        combined_text = transcript or memory_text
        if not combined_text and not audio_filename:
            return jsonify({"message": "Please add text, a transcript, or an audio recording."}), 400

        cursor = connection.execute(
            """
            INSERT INTO memories
                (title, member_id, memory_text, transcript, audio_filename, summary, tags, created_by)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                title or make_title(combined_text, f"Memory of {member['name']}"),
                member_id,
                memory_text,
                transcript,
                audio_filename,
                make_summary(combined_text),
                ",".join(make_tags(combined_text)),
                user["id"],
            ),
        )
        memory_id = cursor.lastrowid
        connection.commit()
        memory = find_memory(connection, memory_id)
        return jsonify(memory_to_dict(memory)), 201
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


@app.get("/api/memories/<int:memory_id>")
@jwt_required()
def get_memory(memory_id):
    user, family = get_current_context()
    if not user or not family:
        return jsonify({"message": "Family not found."}), 404

    connection = connect_family(family["id"])
    try:
        memory = find_memory(connection, memory_id)
        if not memory:
            return jsonify({"message": "Memory not found in your family."}), 404
        return jsonify(memory_to_dict(memory))
    finally:
        connection.close()


@app.get("/api/memories/<int:memory_id>/audio")
@jwt_required()
def memory_audio(memory_id):
    user, family = get_current_context()
    if not user or not family:
        return jsonify({"message": "Family not found."}), 404

    connection = connect_family(family["id"])
    try:
        memory = connection.execute(
            "SELECT audio_filename FROM memories WHERE id = ?", (memory_id,)
        ).fetchone()
    finally:
        connection.close()

    if not memory or not memory["audio_filename"]:
        return jsonify({"message": "Audio not found in your family."}), 404
    return send_from_directory(UPLOAD_DIR, memory["audio_filename"], as_attachment=False)


@app.delete("/api/memories/<int:memory_id>")
@jwt_required()
def delete_memory(memory_id):
    user, family = get_current_context()
    if not user or not family:
        return jsonify({"message": "Family not found."}), 404

    connection = connect_family(family["id"])
    try:
        memory = connection.execute(
            "SELECT audio_filename FROM memories WHERE id = ?", (memory_id,)
        ).fetchone()
        if not memory:
            return jsonify({"message": "Memory not found in your family."}), 404

        connection.execute("DELETE FROM memories WHERE id = ?", (memory_id,))
        connection.commit()

        if memory["audio_filename"]:
            path = os.path.join(UPLOAD_DIR, memory["audio_filename"])
            if os.path.exists(path):
                os.remove(path)

        return jsonify({"message": "Memory deleted."})
    finally:
        connection.close()


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
